from random import uniform,randint
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
print(int(randint(0,1)))
